// backup/sections/Projects.vue
<template>
  <section id="projects" class="max-w-3xl mx-auto py-12 px-4">
    <h2 class="text-2xl font-bold mb-8">{{ lang === 'th' ? 'โปรเจกต์' : 'Projects' }}</h2>
    <div class="mb-6">
      <div class="font-semibold flex items-center">
        <span>Snap Translate - AI Image Translation System</span>
        <a href="https://github.com/pawit5001/SnapTranslate" target="_blank" rel="noopener" class="ml-2 text-blue-600 underline text-sm">[GitHub]</a>
      </div>
      <p class="text-gray-600 text-sm mb-1">Technologies: React, FastAPI, MongoDB, YOLOv8, BLIP, Stable Diffusion XL, Google Translate API, Google TTS</p>
      <p class="mb-1">
        {{ lang === 'th' ?
          'ระบบแปลภาพด้วย AI สำหรับการเรียนรู้ภาษาอื่นๆ รองรับการตรวจจับวัตถุ สร้างคำบรรยาย แปลหลายภาษาพร้อมกัน และสามารถฟังเสียงได้' :
          'AI-powered image translation system for language learning with object detection, image captioning, multi-language translation, and text-to-speech capabilities.'
        }}
      </p>
      <ul class="list-disc pl-6 text-left mb-2">
        <li>{{ lang === 'th' ? 'ตรวจจับวัตถุในภาพด้วย YOLOv8 และสร้างคำบรรยายภาพด้วย BLIP' : 'YOLOv8 object detection and BLIP image captioning' }}</li>
        <li>{{ lang === 'th' ? 'รองรับการแปลภาษามากกว่า 50 ภาษาด้วย Google Translate API' : 'Supports 50+ languages via Google Translate API' }}</li>
        <li>{{ lang === 'th' ? 'สร้างภาพจากข้อความด้วย Stable Diffusion XL และแปลงข้อความเป็นเสียง' : 'AI image generation with Stable Diffusion XL and text-to-speech' }}</li>
        <li>{{ lang === 'th' ? 'ระบบจัดการผู้ใช้ แดชบอร์ดแอดมิน และการแจ้งเตือนผ่าน Discord Webhook' : 'User management, admin dashboard, and Discord webhook notifications' }}</li>
      </ul>
    </div>
    <div class="mb-6">
      <div class="font-semibold flex items-center">
        <span>Gender and Age Prediction System</span>
        <a href="https://github.com/pawit5001/gender-age-prediction" target="_blank" rel="noopener" class="ml-2 text-blue-600 underline text-sm">[GitHub]</a>
      </div>
      <p class="text-gray-600 text-sm mb-1">Technologies: TensorFlow, Keras, OpenCV, EfficientNetB0, Gradio | Dataset: Large facial datasets from Kaggle</p>
      <p class="mb-1">
        {{ lang === 'th' ?
          'ระบบทำนายเพศและอายุจากภาพใบหน้าด้วย Machine Learning พร้อม UI ที่ใช้งานง่าย' :
          'Machine learning-based system for predicting gender and age from facial images with high accuracy, featuring both standalone models and a web interface.'
        }}
      </p>
      <ul class="list-disc pl-6 text-left mb-2">
        <li>{{ lang === 'th' ? 'ความแม่นยำสูง: 99% สำหรับการทำนายเพศ และ 91-92% สำหรับโมเดลรวม' : 'High accuracy: 99% for gender-only model, 91-92% for combined model' }}</li>
        <li>{{ lang === 'th' ? 'ใช้ EfficientNetB0 สำหรับการสกัดฟีเจอร์และมี Data Augmentation' : 'EfficientNetB0 backbone for feature extraction with data augmentation' }}</li>
        <li>{{ lang === 'th' ? 'รองรับทั้งการทำนายเพศเดี่ยวและการทำนายอายุ+เพศพร้อมกัน' : 'Supports both gender-only and combined gender+age predictions' }}</li>
        <li>{{ lang === 'th' ? 'อินเทอร์เฟซ Gradio ที่ใช้งานง่ายพร้อมการแสดงผลแบบเรียลไทม์' : 'User-friendly Gradio web interface with real-time inference' }}</li>
      </ul>
    </div>
    <div class="mb-6">
      <div class="font-semibold flex items-center">
        <span>TravelBlog - Mobile Travel App</span>
        <a href="https://github.com/pawit5001/TravelBlog" target="_blank" rel="noopener" class="ml-2 text-blue-600 underline text-sm">[GitHub]</a>
        <a href="https://www.mediafire.com/file/v2oec2xoyqh92op/TravelBlog.apk/file" target="_blank" rel="noopener" class="ml-2 text-green-600 underline text-sm">[Download APK]</a>
      </div>
      <p class="text-gray-600 text-sm mb-1">Technologies: Flutter, Dart | Platform: Android 5.0+</p>
      <p class="mb-1">
        {{ lang === 'th' ?
          'แอปมือถือสำหรับค้นหาและสำรวจสถานที่ท่องเที่ยว พร้อมคำแนะนำ และรองรับภาษาไทย' :
          'Flutter-based mobile application for discovering and exploring popular travel destinations with travel tips, wishlist functionality, and Thai language support.'
        }}
      </p>
      <ul class="list-disc pl-6 text-left mb-2">
        <li>{{ lang === 'th' ? 'เรียกดูสถานที่ท่องเที่ยวยอดนิยมพร้อมข้อมูลโดยละเอียด' : 'Browse popular destinations with detailed information and tips' }}</li>
        <li>{{ lang === 'th' ? 'บันทึกสถานที่โปรดลงใน Wishlist' : 'Wishlist functionality to save favorite places with image galleries' }}</li>
        <li>{{ lang === 'th' ? 'UI ภาษาไทยพร้อม Design ที่ทันสมัย' : 'Thai language interface with modern Material Design' }}</li>
        <li>{{ lang === 'th' ? 'สร้างด้วย Flutter รองรับหลายแพลตฟอร์ม' : 'Built with Flutter for cross-platform support with downloadable APK' }}</li>
      </ul>
    </div>
    <div class="mb-6">
      <div class="font-semibold flex items-center">
        <span>Sport Equipment Booking System</span>
        <a href="https://github.com/pawit5001/Sport-equipment-booking" target="_blank" rel="noopener" class="ml-2 text-blue-600 underline text-sm">[GitHub]</a>
      </div>
      <p class="text-gray-600 text-sm mb-1">Technologies: PHP, MySQL, Bootstrap 5 | Server: Apache (XAMPP)</p>
      <p class="mb-1">
        {{ lang === 'th' ?
          'ระบบจัดการการยืม-คืนอุปกรณ์กีฬาสำหรับ RMUTTO พร้อมระบบแอดมิน' :
          'Web-based sport equipment borrowing and return management system for RMUTTO with comprehensive admin features.'
        }}
      </p>
      <ul class="list-disc pl-6 text-left mb-2">
        <li>{{ lang === 'th' ? 'การจัดการอุปกรณ์กีฬาแบบครบวงจร: หมวดหมู่, อุปกรณ์กีฬา และผู้รับผิดชอบ' : 'Complete equipment management: categories, items, and PIC' }}</li>
        <li>{{ lang === 'th' ? 'ระบบจองอุปกรณ์กีฬาแบบตะกร้าสินค้า ประวัติการยืม และใบเสร็จ' : 'Booking system with cart, history tracking, and receipt printing' }}</li>
        <li>{{ lang === 'th' ? 'แดชบอร์ดแอดมินพร้อมสถิติและการตั้งค่าระบบ (ระยะเวลายืม, ค่าปรับ)' : 'Admin dashboard with statistics and system settings (max days, late fees)' }}</li>
        <li>{{ lang === 'th' ? 'ระบบสมาชิกและการจัดการบทบาทผู้ใช้' : 'User authentication system with role-based access control' }}</li>
      </ul>
    </div>
  </section>
</template>

<script setup>
const props = defineProps({
  lang: String
});
</script>

// my-portfolio/src/sections/Projects.tsx
import React from "react";

type Props = { lang?: string };

const Projects: React.FC<Props> = ({ lang = "en" }) => (
  <section id="projects" className="max-w-3xl mx-auto py-12 px-4 scroll-mt-20">
    <h2 className="text-2xl font-bold mb-8">{lang === "th" ? "โปรเจกต์" : "Projects"}</h2>

    <div className="mb-6">
      <div className="flex items-center">
        <span className="text-lg md:text-xl font-semibold">Snap Translate</span>
        <span className="ml-3 text-sm md:text-base text-gray-600">{lang === "th" ? "เว็บไซต์แปลภาษาจากรูปภาพ" : "Image Translation Website"}</span>
        <a href="https://github.com/pawit5001/SnapTranslate" target="_blank" rel="noopener noreferrer" className="ml-4 text-blue-600 underline text-sm md:text-base">[GitHub]</a>
      </div>
      <p className="text-gray-600 text-sm mb-1">{lang === "th" ? "เทคโนโลยี: React, FastAPI, MongoDB, YOLOv8, BLIP, Google Translate API" : "Technologies: React, FastAPI, MongoDB, YOLOv8, BLIP, Google Translate API"}</p>
      <p className="text-gray-600 text-sm mb-2">{lang === "th" ? "ระบบแปลภาพด้วย AI สำหรับการเรียนภาษา" : "An AI-powered image translation system for language learning."}</p>

      <ul className="list-disc pl-6 mb-2 text-sm text-gray-700">
        <li>{lang === "th" ? "ตรวจจับวัตถุด้วย YOLOv8 เพื่อทำนายภาพ" : "Object detection with YOLOv8 to locate and classify objects in images"}</li>
        <li>{lang === "th" ? "สร้างคำบรรยายภาพด้วย BLIP เพื่ออธิบายรูปภาพก่อนนำไปแปลภาษา" : "Image captioning using BLIP to generate descriptive captions before translation"}</li>
        <li>{lang === "th" ? "แปลภาพเป็นหลายภาษาได้ เลือกได้มากสุด 5 ภาษาพร้อมกัน" : "Translate image captions into multiple languages (up to 5 simultaneously)"}</li>
        <li>{lang === "th" ? "สร้างภาพจากข้อความ (Stable Diffusion XL)" : "Image generation from text prompts using Stable Diffusion XL"}</li>
        <li>{lang === "th" ? "Discord Log เพื่อดูบันทึกการแปลภาพแบบเรียลไทม์" : "Discord logging to view real-time image translation results"}</li>
      </ul>
    </div>

    <div className="mb-6">
      <div className="flex items-center">
        <span className="text-lg md:text-xl font-semibold">Gender & Age Prediction</span>
        <span className="ml-3 text-sm md:text-base text-gray-600">{lang === "th" ? "ระบบทำนายเพศและอายุ" : "Gender & Age Prediction System"}</span>
        <a href="https://github.com/pawit5001/gender-age-prediction" target="_blank" rel="noopener noreferrer" className="ml-4 text-blue-600 underline text-sm md:text-base">[GitHub]</a>
      </div>

      <p className="text-gray-600 text-sm mb-1">{lang === "th" ? "เทคโนโลยี: Python, TensorFlow, Keras, OpenCV, scikit-learn, Gradio, EfficientNetB0" : "Technologies: Python, TensorFlow, Keras, OpenCV, scikit-learn, Gradio, EfficientNetB0"}</p>
      <p className="text-gray-600 text-sm mb-2">{lang === "th" ? "ระบบทำนายเพศและอายุจากภาพใบหน้าด้วยโมเดล ML" : "A machine learning system for predicting gender and age from facial images."}</p>

      <ul className="list-disc pl-6 mb-2 text-sm text-gray-700">
        <li>{lang === "th" ? "ทำนายเพศและอายุจากรูปภาพคน" : "Gender prediction and age estimation"}</li>
        <li>{lang === "th" ? "การเตรียมข้อมูลก่อนนำไปเทรน (ขนาดรูปภาพ, ปรับมุม, การตรวจจับใบหน้า)" : "Uses EfficientNetB0 backbone; implemented with TensorFlow/Keras. OpenCV is used for image preprocessing (face detection, resizing, normalization)."}</li>
        <li>{lang === "th" ? "รองรับการเทรนโมเดลเป็นชุด หลาย batch พร้อมกัน" : "Can process many images at once (batch) or handle single images instantly (real-time)"}</li>
        <li>{lang === "th" ? "เทรนด้วยชุดข้อมูลภาพใบหน้า พร้อมเทคนิคเพิ่มความหลากหลายของข้อมูล" : "Trained on public face datasets with data augmentation for improved robustness"}</li>
        <li>{lang === "th" ? "อินเตอร์เฟซ: Gradio web app" : "Interfaces: Gradio web app"}</li>
      </ul>
    </div>

    <div className="mb-6">
      <div className="flex items-center">
        <span className="text-lg md:text-xl font-semibold">TravelBlog</span>
        <span className="ml-3 text-sm md:text-base text-gray-600">{lang === "th" ? "แอปมือถือแนะนำสถานที่ท่องเที่ยว" : "Mobile Travel App"}</span>
        <a href="https://github.com/pawit5001/TravelBlog" target="_blank" rel="noopener noreferrer" className="ml-4 text-blue-600 underline text-sm md:text-base">[GitHub]</a>
        <a href="https://www.mediafire.com/file/v2oec2xoyqh92op/TravelBlog.apk/file" target="_blank" rel="noopener noreferrer" className="ml-3 text-green-600 underline text-sm md:text-base">[Download APK]</a>
      </div>
      <p className="text-gray-600 text-sm mb-1">Technologies: Flutter, Dart | Platform: Android</p>
      <p className="mb-1">{lang === "th" ? "Flutter-based mobile application for discovering and exploring popular travel destinations with travel tips, wishlist functionality, and Thai language support." : "Flutter-based mobile application for discovering and exploring popular travel destinations with travel tips, wishlist functionality, and Thai language support."}</p>
      <ul className="list-disc pl-6 mb-2 text-sm text-gray-700">
        <li>{lang === "th" ? "เลือกดูสถานที่ยอดนิยมพร้อมรายละเอียดของสถานที่" : "Browse popular destinations with detailed information and image galleries"}</li>
        <li>{lang === "th" ? "บันทึกสถานที่ที่ชอบด้วยฟีเจอร์ Wishlist" : "Save favorite places using the wishlist feature"}</li>
        <li>{lang === "th" ? "รองรับภาษาไทยเต็มรูปแบบ" : "Full Thai language support (localization)"}</li>
        <li>{lang === "th" ? "ค้นหาและกรองสถานที่ตามหมวดหมู่" : "Search and filter destinations by category"}</li>
      </ul>
    </div>

    <div className="mb-6">
      <div className="flex items-center">
        <span className="text-lg md:text-xl font-semibold">Sport Equipment Booking</span>
        <span className="ml-3 text-sm md:text-base text-gray-600">{lang === "th" ? "ระบบยืม-คืนอุปกรณ์กีฬา" : "Sport Equipment Booking System"}</span>
        <a href="https://github.com/pawit5001/Sport-equipment-booking" target="_blank" rel="noopener noreferrer" className="ml-4 text-blue-600 underline text-sm md:text-base">[GitHub]</a>
      </div>
      <p className="text-gray-600 text-sm mb-1">Technologies: PHP, MySQL, Bootstrap 5 | Server: Apache (XAMPP)</p>
      <p className="text-gray-600 text-sm mb-2">{lang === "th" ? "ระบบยืม-คืนอุปกรณ์กีฬา" : "Web-based sport equipment borrowing & return system"}</p>

      <ul className="list-disc pl-6 text-left mb-2 text-sm text-gray-700">
          <li>{lang === "th" ? "สมัครสมาชิกและเข้าสู่ระบบผู้ใช้ (นักศึกษา/แอดมิน)" : "User signup and login (student/admin)"}</li>
          <li>{lang === "th" ? "เรียกดูอุปกรณ์ จัดใส่ตะกร้า และทำการยืม" : "Browse equipment, add to cart, and borrow items"}</li>
          <li>{lang === "th" ? "การจัดการ: หมวดหมู่, อุปกรณ์, ผู้รับผิดชอบ และการคืนอุปกรณ์ที่ยืม" : "Admin management: categories, equipment, responsible staff, and returns"}</li>
          <li>{lang === "th" ? "ดูประวัติการจอง พิมพ์ใบเสร็จ และสถิติในแดชบอร์ด" : "View booking history, print receipts, and see dashboard statistics"}</li>
          <li>{lang === "th" ? "การตั้งค่าระบบ: ระยะเวลาในการยืมสูงสุดและค่าปรับ" : "System settings: max borrow duration and late fees per day"}</li>
      </ul>
    </div>
  </section>
);

export default Projects;
