// backup/sections/Projects.vue
<template>
  <section id="projects" class="max-w-3xl mx-auto py-12 px-4">
    <h2 class="text-2xl font-bold mb-8">{{ lang === 'th' ? 'โปรเจกต์' : 'Projects' }}</h2>
    <div class="mb-6">
      <div class="font-semibold flex items-center">
        <span>Snap Translate - AI Image Translation System</span>
        <a href="https://github.com/pawit5001/SnapTranslate" target="_blank" rel="noopener" class="ml-2 text-blue-600 underline text-sm">[GitHub]</a>
      </div>
      <p class="text-gray-600 text-sm mb-1">Technologies: React, FastAPI, MongoDB, YOLOv8, BLIP, Stable Diffusion XL, Google Translate API, Google TTS</p>
      <p class="mb-1">
        {{ lang === 'th' ?
          'ระบบแปลภาพด้วย AI สำหรับการเรียนรู้ภาษาอื่นๆ รองรับการตรวจจับวัตถุ สร้างคำบรรยาย แปลหลายภาษาพร้อมกัน และสามารถฟังเสียงได้' :
          'AI-powered image translation system for language learning with object detection, image captioning, multi-language translation, and text-to-speech capabilities.'
        }}
      </p>
      <ul class="list-disc pl-6 text-left mb-2">
        <li>{{ lang === 'th' ? 'ตรวจจับวัตถุในภาพด้วย YOLOv8 และสร้างคำบรรยายภาพด้วย BLIP' : 'YOLOv8 object detection and BLIP image captioning' }}</li>
        <li>{{ lang === 'th' ? 'รองรับการแปลภาษามากกว่า 50 ภาษาด้วย Google Translate API' : 'Supports 50+ languages via Google Translate API' }}</li>
        <li>{{ lang === 'th' ? 'สร้างภาพจากข้อความด้วย Stable Diffusion XL และแปลงข้อความเป็นเสียง' : 'AI image generation with Stable Diffusion XL and text-to-speech' }}</li>
        <li>{{ lang === 'th' ? 'ระบบจัดการผู้ใช้ แดชบอร์ดแอดมิน และการแจ้งเตือนผ่าน Discord Webhook' : 'User management, admin dashboard, and Discord webhook notifications' }}</li>
      </ul>
    </div>
    <div class="mb-6">
      <div class="font-semibold flex items-center">
        <span>Gender and Age Prediction System</span>
        <a href="https://github.com/pawit5001/gender-age-prediction" target="_blank" rel="noopener" class="ml-2 text-blue-600 underline text-sm">[GitHub]</a>
      </div>
      <p class="text-gray-600 text-sm mb-1">Technologies: TensorFlow, Keras, OpenCV, EfficientNetB0, Gradio | Dataset: Large facial datasets from Kaggle</p>
      <p class="mb-1">
        {{ lang === 'th' ?
          'ระบบทำนายเพศและอายุจากภาพใบหน้าด้วย Machine Learning พร้อม UI ที่ใช้งานง่าย' :
          'Machine learning-based system for predicting gender and age from facial images with high accuracy, featuring both standalone models and a web interface.'
        }}
      </p>
      <ul class="list-disc pl-6 text-left mb-2">
        <li>{{ lang === 'th' ? 'ความแม่นยำสูง: 99% สำหรับการทำนายเพศ และ 91-92% สำหรับโมเดลรวม' : 'High accuracy: 99% for gender-only model, 91-92% for combined model' }}</li>
        <li>{{ lang === 'th' ? 'ใช้ EfficientNetB0 สำหรับการสกัดฟีเจอร์และมี Data Augmentation' : 'EfficientNetB0 backbone for feature extraction with data augmentation' }}</li>
        <li>{{ lang === 'th' ? 'รองรับทั้งการทำนายเพศเดี่ยวและการทำนายอายุ+เพศพร้อมกัน' : 'Supports both gender-only and combined gender+age predictions' }}</li>
        <li>{{ lang === 'th' ? 'อินเทอร์เฟซ Gradio ที่ใช้งานง่ายพร้อมการแสดงผลแบบเรียลไทม์' : 'User-friendly Gradio web interface with real-time inference' }}</li>
      </ul>
    </div>
    <div class="mb-6">
      <div class="font-semibold flex items-center">
        <span>TravelBlog - Mobile Travel App</span>
        <a href="https://github.com/pawit5001/TravelBlog" target="_blank" rel="noopener" class="ml-2 text-blue-600 underline text-sm">[GitHub]</a>
        <a href="https://www.mediafire.com/file/v2oec2xoyqh92op/TravelBlog.apk/file" target="_blank" rel="noopener" class="ml-2 text-green-600 underline text-sm">[Download APK]</a>
      </div>
      <p class="text-gray-600 text-sm mb-1">Technologies: Flutter, Dart | Platform: Android 5.0+</p>
      <p class="mb-1">
        {{ lang === 'th' ?
          'แอปมือถือสำหรับค้นหาและสำรวจสถานที่ท่องเที่ยว พร้อมคำแนะนำ และรองรับภาษาไทย' :
          'Flutter-based mobile application for discovering and exploring popular travel destinations with travel tips, wishlist functionality, and Thai language support.'
        }}
      </p>
      <ul class="list-disc pl-6 text-left mb-2">
        <li>{{ lang === 'th' ? 'เรียกดูสถานที่ท่องเที่ยวยอดนิยมพร้อมข้อมูลโดยละเอียด' : 'Browse popular destinations with detailed information and tips' }}</li>
        <li>{{ lang === 'th' ? 'บันทึกสถานที่โปรดลงใน Wishlist' : 'Wishlist functionality to save favorite places with image galleries' }}</li>
        <li>{{ lang === 'th' ? 'UI ภาษาไทยพร้อม Design ที่ทันสมัย' : 'Thai language interface with modern Material Design' }}</li>
        <li>{{ lang === 'th' ? 'สร้างด้วย Flutter รองรับหลายแพลตฟอร์ม' : 'Built with Flutter for cross-platform support with downloadable APK' }}</li>
      </ul>
    </div>
    <div class="mb-6">
      <div class="font-semibold flex items-center">
        <span>Sport Equipment Booking System</span>
        <a href="https://github.com/pawit5001/Sport-equipment-booking" target="_blank" rel="noopener" class="ml-2 text-blue-600 underline text-sm">[GitHub]</a>
      </div>
      <p class="text-gray-600 text-sm mb-1">Technologies: PHP, MySQL, Bootstrap 5 | Server: Apache (XAMPP)</p>
      <p class="mb-1">
        {{ lang === 'th' ?
          'ระบบจัดการการยืม-คืนอุปกรณ์กีฬาสำหรับ RMUTTO พร้อมระบบแอดมิน' :
          'Web-based sport equipment borrowing and return management system for RMUTTO with comprehensive admin features.'
        }}
      </p>
      <ul class="list-disc pl-6 text-left mb-2">
        <li>{{ lang === 'th' ? 'การจัดการอุปกรณ์กีฬาแบบครบวงจร: หมวดหมู่, อุปกรณ์กีฬา และผู้รับผิดชอบ' : 'Complete equipment management: categories, items, and PIC' }}</li>
        <li>{{ lang === 'th' ? 'ระบบจองอุปกรณ์กีฬาแบบตะกร้าสินค้า ประวัติการยืม และใบเสร็จ' : 'Booking system with cart, history tracking, and receipt printing' }}</li>
        <li>{{ lang === 'th' ? 'แดชบอร์ดแอดมินพร้อมสถิติและการตั้งค่าระบบ (ระยะเวลายืม, ค่าปรับ)' : 'Admin dashboard with statistics and system settings (max days, late fees)' }}</li>
        <li>{{ lang === 'th' ? 'ระบบสมาชิกและการจัดการบทบาทผู้ใช้' : 'User authentication system with role-based access control' }}</li>
      </ul>
    </div>
  </section>
</template>

<script setup>
const props = defineProps({
  lang: String
});
</script>

// src/sections/Projects.tsx
import React from "react";

type Props = { lang?: string };

const Projects: React.FC<Props> = ({ lang = "en" }) => (
  <section id="projects" className="max-w-3xl mx-auto py-12 px-4 scroll-mt-20">
    <h2 className="text-2xl font-bold mb-8">
      {lang === "th" ? "ผลงานโปรเจกต์" : "Projects"}
    </h2>

    {/* Snap Translate */}
    <div className="mb-6">
      <div className="flex items-center flex-wrap">
        <span className="text-lg md:text-xl font-semibold">Snap Translate</span>
        <span className="ml-3 text-sm md:text-base text-gray-600">
          {lang === "th" ? "เว็บแอปพลิเคชันแปลภาษาจากภาพด้วย AI" : "AI Image Translation Web Application"}
        </span>
        <a
          href="https://github.com/pawit5001/SnapTranslate"
          target="_blank"
          rel="noopener noreferrer"
          className="ml-4 text-blue-600 underline text-sm md:text-base"
        >
          [GitHub]
        </a>
      </div>

      <p className="text-gray-600 text-sm mb-1">
        {lang === "th"
          ? "เทคโนโลยีที่ใช้: React, FastAPI, MongoDB, YOLOv8, BLIP, Google Translate API, Stable Diffusion XL"
          : "Technologies: React, FastAPI, MongoDB, YOLOv8, BLIP, Google Translate API, Stable Diffusion XL"}
      </p>

      <p className="text-gray-600 text-sm mb-2">
        {lang === "th"
          ? "ระบบแปลภาษาจากภาพโดยใช้ AI ผสานเทคโนโลยี Computer Vision และ NLP"
          : "An AI-powered system combining Computer Vision and NLP for image-based translation."}
      </p>

      <ul className="list-disc pl-6 mb-2 text-sm text-gray-700">
        <li>
          {lang === "th"
            ? "ตรวจจับและจำแนกวัตถุในภาพด้วย YOLOv8 เพื่อระบุวัตถุหลายชนิดในภาพอย่างแม่นยำ"
            : "Implemented object detection using YOLOv8 to locate and classify multiple objects in images"}
        </li>
        <li>
          {lang === "th"
            ? "สร้างคำบรรยายภาพอัตโนมัติด้วย BLIP เพื่อรองรับการแปลรูปภาพที่หลากหลายมากยิ่งขึ้น"
            : "Integrated BLIP image captioning to generate contextual descriptions prior to translation"}
        </li>
        <li>
          {lang === "th"
            ? "รองรับการแปลคำบรรยายภาพเป็นภาษาต่าง ๆ ได้พร้อมกันสูงสุด 5 ภาษา"
            : "Enabled multi-language translation of image captions, supporting up to 5 languages simultaneously"}
        </li>
        <li>
          {lang === "th"
            ? "สร้างภาพจากข้อความด้วย Stable Diffusion XL เพื่อเพิ่มความเข้าใจและความน่าสนใจของเนื้อหา"
            : "Implemented text-to-image generation using Stable Diffusion XL"}
        </li>
        <li>
          {lang === "th"
            ? "บันทึกผลการแปลภาพแบบเรียลไทม์ผ่าน Discord เพื่อการติดตามและตรวจสอบ"
            : "Built real-time Discord logging to monitor image translation results"}
        </li>
      </ul>
    </div>

    {/* Gender & Age Prediction */}
    <div className="mb-6">
      <div className="flex items-center flex-wrap">
        <span className="text-lg md:text-xl font-semibold">Gender & Age Prediction</span>
        <span className="ml-3 text-sm md:text-base text-gray-600">
          {lang === "th" ? "ระบบทำนายเพศและอายุด้วย AI" : "Gender & Age Prediction System"}
        </span>
        <a
          href="https://github.com/pawit5001/gender-age-prediction"
          target="_blank"
          rel="noopener noreferrer"
          className="ml-4 text-blue-600 underline text-sm md:text-base"
        >
          [GitHub]
        </a>
      </div>

      <p className="text-gray-600 text-sm mb-1">
        {lang === "th"
          ? "เทคโนโลยีที่ใช้: Python, TensorFlow, Keras, OpenCV, Gradio, EfficientNetB0"
          : "Technologies: Python, TensorFlow, Keras, OpenCV, Gradio, EfficientNetB0"}
      </p>

      <p className="text-gray-600 text-sm mb-2">
        {lang === "th"
          ? "ระบบ Machine Learning สำหรับทำนายเพศและอายุจากภาพใบหน้าอย่างแม่นยำและรวดเร็ว"
          : "A machine learning system for gender classification and age estimation from facial images."}
      </p>

      <ul className="list-disc pl-6 mb-2 text-sm text-gray-700">
        <li>
          {lang === "th"
            ? "พัฒนาโมเดล Deep Learning สำหรับทำนายเพศและอายุจากภาพใบหน้า"
            : "Developed a deep learning model for gender prediction and age estimation"}
        </li>
        <li>
          {lang === "th"
            ? "ใช้ EfficientNetB0 เป็นโครงข่ายหลัก พร้อมเตรียมข้อมูลภาพด้วย OpenCV (ตรวจจับใบหน้า ปรับขนาด และปรับมาตรฐาน)"
            : "Implemented EfficientNetB0 backbone with TensorFlow/Keras and OpenCV-based preprocessing (face detection, resizing, normalization)"}
        </li>
        <li>
          {lang === "th"
            ? "รองรับการประมวลผลทั้งแบบเรียลไทม์และแบบกลุ่ม (batch)"
            : "Supported both real-time single-image inference and batch processing"}
        </li>
        <li>
          {lang === "th"
            ? "ฝึกโมเดลด้วยชุดข้อมูลสาธารณะ พร้อมเทคนิค Data Augmentation เพื่อเพิ่มความแม่นยำ"
            : "Trained on public face datasets with data augmentation to improve robustness and generalization"}
        </li>
        <li>
          {lang === "th"
            ? "พัฒนาอินเทอร์เฟซทดลองใช้งานผ่าน Gradio เพื่อให้ผู้ใช้สามารถทดสอบระบบได้ง่าย"
            : "Built an interactive Gradio web interface for model demonstration"}
        </li>
      </ul>
    </div>

{/* TravelBlog */}
<div className="mb-6">
<div className="flex items-center flex-wrap">
  <span className="text-lg md:text-xl font-semibold">TravelBlog</span>
  <span className="ml-3 text-sm md:text-base text-gray-600">
    {lang === "th" ? "แอปมือถือแนะนำสถานที่ท่องเที่ยว" : "Mobile Travel Application"}
  </span>
  <a
    href="https://github.com/pawit5001/TravelBlog"
    target="_blank"
    rel="noopener noreferrer"
    className="ml-4 text-blue-600 underline text-sm md:text-base"
  >
    [GitHub]
  </a>
  <a
    href="https://www.mediafire.com/file/v2oec2xoyqh92op/TravelBlog.apk/file"
    target="_blank"
    rel="noopener noreferrer"
    className="ml-3 text-green-600 underline text-sm md:text-base"
  >
    [APK]
  </a>
</div>

<p className="text-gray-600 text-sm mb-1">
  Technologies: Flutter, Dart | Platform: Android
</p>

<p className="text-gray-600 text-sm mb-2">
    {lang === "th"
      ? "แอปมือถือที่พัฒนาด้วย Flutter สำหรับค้นหาและบันทึกสถานที่ท่องเที่ยว พร้อมรองรับภาษาไทยอย่างสมบูรณ์"
      : "A Flutter-based mobile application for discovering and exploring travel destinations with localization support."}
</p>

<ul className="list-disc pl-6 mb-2 text-sm text-gray-700">
  <li>
    {lang === "th"
      ? "เรียกดูสถานที่ท่องเที่ยวยอดนิยม พร้อมรายละเอียดและแกลเลอรีรูปภาพ"
      : "Browse popular travel destinations with detailed information and image galleries"}
  </li>
  <li>
    {lang === "th"
      ? "บันทึกสถานที่ที่สนใจด้วยฟีเจอร์ Wishlist เพื่อการเข้าถึงที่รวดเร็ว"
      : "Implemented a wishlist feature to save favorite destinations"}
  </li>
  <li>
    {lang === "th"
      ? "ค้นหาและกรองสถานที่ท่องเที่ยวตามหมวดหมู่ได้อย่างสะดวก"
      : "Enabled search and filtering of destinations by category"}
  </li>
  <li>
    {lang === "th"
      ? "รองรับการใช้งานภาษาไทยอย่างสมบูรณ์แบบ"
      : "Provided full Thai language localization"}
  </li>
</ul>
</div>

    {/* Sport Equipment Booking */}
    <div className="mb-6">
      <div className="flex items-center flex-wrap">
        <span className="text-lg md:text-xl font-semibold">Sport Equipment Booking</span>
        <span className="ml-3 text-sm md:text-base text-gray-600">
          {lang === "th" ? "ระบบจองและยืม-คืนอุปกรณ์กีฬา" : "Sport Equipment Booking System"}
        </span>
        <a
          href="https://github.com/pawit5001/Sport-equipment-booking"
          target="_blank"
          rel="noopener noreferrer"
          className="ml-4 text-blue-600 underline text-sm md:text-base"
        >
          [GitHub]
        </a>
      </div>

      <p className="text-gray-600 text-sm mb-1">
        Technologies: PHP, MySQL, Bootstrap 5 | Server: Apache (XAMPP)
      </p>

      <p className="text-gray-600 text-sm mb-2">
        {lang === "th"
          ? "ระบบเว็บสำหรับบริหารจัดการการจองและยืม-คืนอุปกรณ์กีฬาอย่างมีประสิทธิภาพ"
          : "A web-based system for managing sport equipment borrowing and returns."}
      </p>

      <ul className="list-disc pl-6 mb-2 text-sm text-gray-700">
        <li>
          {lang === "th"
            ? "ระบบสมัครสมาชิกและเข้าสู่ระบบ พร้อมแยกสิทธิ์การใช้งานระหว่างผู้ใช้ทั่วไปและผู้ดูแลระบบ"
            : "Implemented user authentication with role-based access (student/admin)"}
        </li>
        <li>
          {lang === "th"
            ? "เลือกดูอุปกรณ์ เพิ่มลงตะกร้า และทำรายการยืมได้อย่างสะดวก"
            : "Enabled users to browse equipment, add items to cart, and submit borrowing requests"}
        </li>
        <li>
          {lang === "th"
            ? "ระบบจัดการอุปกรณ์ หมวดหมู่ ผู้รับผิดชอบ และการคืน สำหรับผู้ดูแลระบบ"
            : "Developed admin management features for categories, equipment inventory, responsible staff, and returns"}
        </li>
        <li>
          {lang === "th"
            ? "แสดงประวัติการยืม ใบเสร็จ และสถิติการใช้งานผ่านแดชบอร์ด"
            : "Provided booking history, receipt printing, and dashboard statistics"}
        </li>
        <li>
          {lang === "th"
            ? "ตั้งค่าระยะเวลาการยืมสูงสุดและคำนวณค่าปรับรายวันโดยอัตโนมัติ"
            : "Configured system settings including maximum borrow duration and late fee calculation per day"}
        </li>
      </ul>
    </div>
  </section>
);

export default Projects;
